## Reference: https://pages.github.com/versions/
## >> bundle install

source 'https://rubygems.org'

## gem 'ruby', '2.3.1'
gem 'jekyll', '3.3.0'
gem 'jekyll-sass-converter', '1.3.0'
gem 'kramdown', '1.11.1'
gem 'liquid', '3.0.6'
gem 'rouge', '1.11.1'
gem 'github-pages-health-check', '1.2.0'
gem 'jemoji', '0.7.0'
gem 'jekyll-mentions', '1.2.0'
gem 'jekyll-redirect-from', '0.11.0'
gem 'jekyll-sitemap', '0.12.0'
gem 'jekyll-feed', '0.8.0'
gem 'jekyll-gist', '1.4.0'
gem 'jekyll-paginate', '1.1.0'
gem 'jekyll-coffeescript', '1.0.1'
gem 'jekyll-seo-tag', '2.1.0'
gem 'jekyll-github-metadata', '2.2.0'
gem 'jekyll-avatar', '0.4.2'
gem 'listen', '3.0.6'
gem 'activesupport', '4.2.7'
gem 'minima', '2.0.0'
gem 'jekyll-swiss', '0.4.0'
gem 'github-pages', '104'
gem 'html-pipeline', '2.4.2'
gem 'sass', '3.4.22'
gem 'safe_yaml', '1.0.4'
gem 'pygments.rb'
gem 'redcarpet'
